apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: skillpulse-dev
  labels:
    app: frontend
    environment: dev
    app.kubernetes.io/name: frontend
    app.kubernetes.io/part-of: skillpulse
    app.kubernetes.io/component: web
    app.kubernetes.io/environment: dev

  annotations:
    argocd.argoproj.io/sync-wave: "2"

spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: http
      nodePort: 30080
      name: http
      protocol: TCP
  selector:
    app: frontend