apiVersion: v1
kind: Secret

metadata:
  name: db-credentials
  namespace: skillpulse-dev

type: Opaque

stringData:
  root-password: root123
  database: skillpulse
  user: skillpulse
  password: skillpulse123