apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: skillpulse-dev
type: Opaque

stringData:
  root-password: demo-root-password
  database: skillpulse
  user: demo-user
  password: demo-password