name: gitops-CI

on:
  push:
    branches: [main]
    tags:
      - 'v*'

concurrency:
  group: gitops-ci
  cancel-in-progress: true

env:
  REGISTRY: docker.io
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}  

jobs:

  setup:
    name: Setup Variables
    runs-on: ubuntu-latest

    outputs:
      image_tag: ${{ steps.vars.outputs.image_tag }}
      is_release: ${{ steps.vars.outputs.is_release }}

    steps:
      - name: Set Variables
        id: vars
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            echo "image_tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
            echo "is_release=true" >> $GITHUB_OUTPUT
          else
            echo "image_tag=main-${GITHUB_SHA::7}" >> $GITHUB_OUTPUT
            echo "is_release=false" >> $GITHUB_OUTPUT
          fi  

  docker-build:
    name: Docker-build
    runs-on: ubuntu-latest
    needs: setup

    strategy:
      matrix:
        include:
          - image: skillpulse-backend
            context: ./backend
            dockerfile: ./backend/Dockerfile

          - image: skillpulse-frontend
            context: ./frontend
            dockerfile: ./frontend/Dockerfile

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Docker login
        uses: docker/login-action@v4
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Build and Push CI Image
        uses: docker/build-push-action@v7
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.dockerfile }}
          push: true
          tags: |
            ${{ env.DOCKERHUB_USERNAME }}/${{ matrix.image }}:unstable-${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest
    needs:
      - setup 
      - docker-build

    strategy:
      matrix:
        include:
          - image: skillpulse-backend
          - image: skillpulse-frontend

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Trivy Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.DOCKERHUB_USERNAME }}/${{ matrix.image }}:unstable-${{ github.sha }}
          format: table
          exit-code: 1
          ignore-unfixed: true
          severity: CRITICAL

      - name: Run Checkov Scan
        uses: bridgecrewio/checkov-action@master
        with:
          directory: .
          framework: dockerfile,github_actions
          soft_fail: true
          output_format: cli,sarif
          log_level: DEBUG

  smoke-test:
    name: Smoke Test
    runs-on: ubuntu-latest
    needs: security-scan

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create .env file
        run: |
          cat <<EOF > .env
          MYSQL_ROOT_PASSWORD= ${{secrets.MYSQL_ROOT_PASSWORD}}
          DB_NAME=skillpulse
          DB_USER=skillpulse
          DB_PASSWORD= ${{secrets.DB_PASSWORD}}
          DOCKERHUB_USERNAME=$DOCKERHUB_USERNAME
          IMAGE_TAG=unstable-${GITHUB_SHA}
          EOF

      - name: Start Containers
        run: |
             docker compose pull
             docker compose up -d

      - name: Wait for Services
        run: sleep 20

      - name: Backend Health Check
        run: curl --fail http://localhost/health

      - name: Stop Containers
        if: always()
        run: docker compose down -v

  push-images:
      name: Promote image to stable tags
      runs-on: ubuntu-latest
      needs: 
        - setup
        - security-scan
        - smoke-test

      strategy:
        matrix:
          include:
            - image: skillpulse-backend
            - image: skillpulse-frontend

      steps:

        - name: Login to DockerHub
          uses: docker/login-action@v4
          with:
            username: ${{ env.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

        - name: Pull unstable image
          run: |
            docker pull \
            $DOCKERHUB_USERNAME/${{ matrix.image }}:unstable-${GITHUB_SHA}

        - name: Promote stable tag
          run: |
            docker tag \
            $DOCKERHUB_USERNAME/${{ matrix.image }}:unstable-${GITHUB_SHA} \
            $DOCKERHUB_USERNAME/${{ matrix.image }}:${{ needs.setup.outputs.image_tag }}

        - name: Push stable tag
          run: |
            docker push \
            $DOCKERHUB_USERNAME/${{ matrix.image }}:${{ needs.setup.outputs.image_tag }}            

        - name: Promote latest tag
          if: needs.setup.outputs.is_release == 'true'
          run: |
            docker tag \
            $DOCKERHUB_USERNAME/${{ matrix.image }}:unstable-${GITHUB_SHA} \
            $DOCKERHUB_USERNAME/${{ matrix.image }}:latest
                  
            docker push \
            $DOCKERHUB_USERNAME/${{ matrix.image }}:latest