name: gitops-CI

on:
  push:
    branches: [main]

concurrency:
  group: gitops-ci
  cancel-in-progress: true

env:
  REGISTRY: docker.io
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}  

jobs:

  docker-build:
    name: Docker-build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - image: skillpulse-backend
            context: ./backend
            dockerfile: ./backend/Dockerfile

          - image: skillpulse-frontend
            context: ./frontend
            dockerfile: ./frontend/Dockerfile

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Docker login
        uses: docker/login-action@v4
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Build Docker Image
        run: |
          docker build \
            -t $DOCKERHUB_USERNAME/${{ matrix.image }}:latest \
            -t $DOCKERHUB_USERNAME/${{ matrix.image }}:${{ github.sha }} \
            -f ${{ matrix.dockerfile }} \
            ${{ matrix.context }}
          
      - name: Save Docker Image
        run: |
          docker save \
            -o ${{ matrix.image }}.tar \
            $DOCKERHUB_USERNAME/${{ matrix.image }}:latest

      - name: Upload Docker Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.image }}
          path: ${{ matrix.image }}.tar

  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest
    needs: docker-build

    strategy:
      matrix:
        include:
          - image: skillpulse-backend
          - image: skillpulse-frontend

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Docker Artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ matrix.image }}

      - name: Load Docker Image
        run: |
          docker load -i ${{ matrix.image }}.tar

      - name: Run Trivy Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.DOCKERHUB_USERNAME }}/${{ matrix.image }}:latest
          format: table
          exit-code: 1
          ignore-unfixed: true
          severity: CRITICAL

      - name: Run Checkov Scan
        uses: bridgecrewio/checkov-action@master
        with:
          directory: .
          framework: dockerfile,github_actions
          soft_fail: true
          output_format: cli,sarif
          log_level: DEBUG

  smoke-test:
    name: Smoke Test
    runs-on: ubuntu-latest
    needs: security-scan

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Backend Artifact
        uses: actions/download-artifact@v4
        with:
          name: skillpulse-backend

      - name: Download Frontend Artifact
        uses: actions/download-artifact@v4
        with:
          name: skillpulse-frontend

      - name: Load Backend Image
        run: docker load -i skillpulse-backend.tar

      - name: Load Frontend Image
        run: docker load -i skillpulse-frontend.tar

      - name: Create .env file
        run: |
          cat <<EOF > .env
          MYSQL_ROOT_PASSWORD= ${{secrets.MYSQL_ROOT_PASSWORD}}
          DB_NAME=skillpulse
          DB_USER=skillpulse
          DB_PASSWORD= ${{secrets.DB_PASSWORD}}
          DOCKERHUB_USERNAME=$DOCKERHUB_USERNAME
          EOF

      - name: Start Containers
        run: docker compose up -d --build

      - name: Wait for Services
        run: sleep 20

      - name: Backend Health Check
        run: curl --fail http://localhost/health

      - name: Stop Containers
        if: always()
        run: docker compose down -v

  push-images:
      name: Push Docker Images
      runs-on: ubuntu-latest
      needs: smoke-test

      strategy:
        matrix:
          include:
            - image: skillpulse-backend
            - image: skillpulse-frontend

      steps:
        - name: Checkout Repository
          uses: actions/checkout@v4

        - name: Login to DockerHub
          uses: docker/login-action@v4
          with:
            username: ${{ env.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

        - name: Download Docker Image Artifact
          uses: actions/download-artifact@v4
          with:
            name: ${{ matrix.image }}

        - name: Load Backend Image
          run: docker load -i ${{ matrix.image }}.tar

        - name: Retag Docker Image
          run: |
            docker tag \
            $DOCKERHUB_USERNAME/${{ matrix.image }}:latest \
            $DOCKERHUB_USERNAME/${{ matrix.image }}:${{ github.sha }}

        - name: Push Latest Tag
          run: docker push $DOCKERHUB_USERNAME/${{ matrix.image }}:latest

        - name: Push SHA Tag
          run: docker push $DOCKERHUB_USERNAME/${{ matrix.image }}:${{ github.sha }}